### ISSUE TITLE
createContext initial value

### ISSUE THREAD

**Issue by luwes** [WebReflection/augmentor#10]
Could `createContext()` already take an initial argument?
Would be a bit cleaner if it would be possible.

`const ctx = createContext(store)`

instead of

```js
const ctx = createContext()
ctx.provide(store)
```

**Comment by WebReflection** [comment]
is that how `React.createContext()` works?

**Comment by luwes** [comment]
Yup, it's possible to pass a default value there.
https://reactjs.org/docs/context.html#reactcreatecontext

**Comment by WebReflection** [comment]
done
