### ISSUE TITLE
Extending hooks - third party hook libs

### ISSUE THREAD

**Issue by luwes** [WebReflection/augmentor#11]
I'm having a hard time getting a standalone redux hook to work.
Some code below. I think it might be a bug.

I know I put `swiss-element` but it mostly exports all the hooks from `augmentor` besides a small adjustment of `useEffect`.

The browser error that is shown:

<img width="1252" alt="screen shot 2019-01-27 at 10 26 02 pm" src="https://user-images.githubusercontent.com/360826/51813088-8c830380-2282-11e9-9c41-b6770aaf97ea.png">

The `now` variable is null. Seems to be caused by duplicate code of a separate import of augmentor in the main library and another in the standalone redux hook library.

```js
import {
  useEffect,
  createContext as cc,
  useContext,
  useState
} from 'swiss-element';

import shallowEqual from './shallow-equal.js';

let reduxContext;
export function createContext(store) {
  reduxContext = cc();
  reduxContext.provide(store);
}

export function useSelector(selector) {
  const store = useContext(reduxContext);
  const { getState } = store;
  const [result, setResult] = useState(selector(getState()));

  return useEffect(
    store.subscribe(() => {
      const nextResult = selector(getState());
      if (shallowEqual(nextResult, result)) return;
      setResult(nextResult);
    }),
  );
}

export function useActionCreator(actionCreator) {
  const { dispatch } = useContext(reduxContext);
  return (...args) => dispatch(actionCreator(...args));
}
```

**Comment by WebReflection** [comment]
whenever you'll be able to provide code related to this library that breaks I'll be able to help.

_mostly the same code_, as well as _small adjustments_ aren't a way for me to understand what's going on.

I also don't know what is the following about

> Seems to be caused by duplicate code of a separate import of augmentor in the main library and another in the standalone redux hook library.

so please reduce the issue to this library only, or I won't manage to find a fix, thanks.

**Comment by luwes** [comment]
cool, I'll try to get something together. 

It's caused by these module variables `now` and `id` I think.
https://github.com/WebReflection/augmentor/blob/master/esm/core.js#L1

For example when you create a package just for a custom hook, say you want to extend the `useEffect` hook. `core.js` will also be pulled in along with those side effects. 

In your main library you will import the default `augmentor` which will also pull in `core.js` creating new side effects, next you'll import your custom hook package and you run `useCustomHook` but at that point 2 versions of `now` and `id` are created that don't have anything in common and the custom hook will not work.

**Comment by WebReflection** [comment]
this makes no sense, 'cause modules/files are imported only once.

You don't have direct access ever to both `now` or `id` and those are there to define indirectly all hooks so I don't understand what you are saying.

Can you please write a piece of code that fails the way you are describing?

**Comment by luwes** [comment]
maybe I'm getting some fundamental thing wrong but say this is a standalone extended hook I want to publish to npm.

```js
import { useEffect } from "augmentor";

export function useSelector(selector) {
  useEffect(selector);
  console.log(99);
}
```

when this is bundled via rollup it turns into

```js
let now = null;
const current = () => now;
const empty = [];
const diff = (a, b) => (a.length !== b.length || a.some(diverse, b));
let id = 0;
const uid = () => '_$' + id++;
const unstacked = id => {
  const {[id]: state, update} = now;
  const {i, stack} = state;
  state.i++;
  return {i, stack, update, unknown: i === stack.length};
};
function diverse(value, i) {
  return value !== this[i];
}

const id$1 = uid();
const create = (always, check, inputs, raf, cb, stack, i) => {
  const info = {
    always,
    cb,
    check,
    clean: null,
    inputs,
    raf,
    t: 0,
    update: check,
    fn: () => {
      set(stack[i], info.cb());
    }
  };
  return info;
};
const effect = raf => (cb, refs) => {
  const {i, stack, unknown} = unstacked(id$1);
  const comp = refs || empty;
  if (unknown) {
    const always = comp === empty;
    const check = always || !raf || typeof comp !== typeof effect;
    if (always || !raf || typeof comp !== typeof effect) {
      stack.push(create(always, check, comp, raf, cb, stack, i));
    } else {
      current().external.push(result => refs(cb, result));
      stack.push(create(always, always, empty, raf, effect, stack, i));
    }
  } else {
    const info = stack[i];
    const {check, always, inputs} = info;
    if (check && (always || diff(inputs, comp))) {
      info.cb = cb;
      info.inputs = comp;
      info.update = true;
    }
  }
};
const set = (info, clean) => {
  info.t = 0;
  info.clean = clean;
};
const useEffect = effect(true);

const id$2 = uid();

const id$3 = uid();

const id$4 = uid();

const id$5 = uid();

function useSelector(selector) {
  useEffect(selector);
  console.log(99);
}

export { useSelector };
```

now when I try to import this into my main library which also imports other augmentor functions and then bundles them via rollup. I have duplicate code which works independently and the new `useSelector` hook won't work.

**Comment by luwes** [comment]
my bad, I looked at how all the third-party react hooks are made and they define `react` as a peer dependency. So not really including or resolving, defined as an external in rollup...

thanks for the feedback.

**Comment by WebReflection** [comment]
yep, peer dependency sounds the only way to go indeed 👍
