### ISSUE TITLE
useState functional updates

### ISSUE THREAD

**Issue by luwes** [WebReflection/augmentor#12]
The setter returned from `useState` could also accept a function

See here for more info: https://reactjs.org/docs/hooks-reference.html#functional-updates.

For example this should be equivalent:

```js

	const [count, setCount] = useState(0);

	setCount(count + 1);

	// or

	setCount(prevcount => prevcount + 1); // argument name can be different

```

**Comment by WebReflection** [comment]
can you please confirm 0.2.6 works as expected?

**Comment by luwes** [comment]
Awesome thank you! Confirmed it works 👍
