### ISSUE TITLE
useEffect is called once per frame

### ISSUE THREAD

**Issue by dy** [WebReflection/augmentor#22]
```js
import augment, { useEffect } from 'augmentor'

let f = augment(() => useEffect(() => console.log('augmentor')))
f()
f()
f()
```
From this example, the `useEffect` is called only once.
React calls `useEffect` any time `render` is called ([sandbox](https://codesandbox.io/s/exciting-almeida-8peiw?fontsize=14&hidenavigation=1&theme=dark)).

Is that so by design?

**Comment by WebReflection** [comment]
> Is that so by design?

yes, but you have `useLayoutEffect` if you want stuff to run synchronously, and every single time, after callback invocation.

what's your use case for wanting effects to be called many consecutively times?

**Comment by WebReflection** [comment]
although ... now that I think about it, if there are handlers or other things involved, not force-flushing on each invoke might cause disasters ... so I think this should be fixed (soon).

**Comment by WebReflection** [comment]
Fixed, it's now guaranteed to force-flush on repeated runs.
