### ISSUE TITLE
`contextual` does not clean up via `dropEffect`

### ISSUE THREAD

**Issue by dy** [WebReflection/augmentor#23]
```js
let {contextual, augmentor, useEffect, dropEffect} = await import('augmentor')
  let f = contextual(() => {
    useEffect(() => {
      console.log('in')
      return () => {
        console.log('out')
      }
    })
  })
  f()
  await time(10)
  dropEffect(f)
```
As we see, `'out'` is never logged. Although that works fine with just `augmentor` entry.

**Comment by WebReflection** [comment]
> Although that works fine with just augmentor entry.

what do you mean?

**Comment by WebReflection** [comment]
Anyway, as I could reproduce the issue, this has been fixed.

However, just in case, `contextual` makes sense only if you access `this` within the function, so that `contextual` with arrow functions can be considered a bad practice/footgun (not internal arrows, just arrows passed to contextual).
