### ISSUE TITLE
Asynchronous functions lose effects

### ISSUE THREAD

**Issue by dy** [WebReflection/augmentor#24]
```js
import a from 'augmentor'
let f1 = a.augmentor(async () => {
  let [x, setx] = a.useState(0);
  console.log(x)
  await '';
  a.useEffect(() => {
    setx(1)
  }, [])
});
```
Function isn't updated here. Is that by design?

**Comment by WebReflection** [comment]
Yeah, that cannot work, and it wouldn't work in React neither:
https://itnext.io/react-async-components-classes-vs-hooks-1a9068b61b3f

You should likely separate data behaviors from hooks logic, as described in the link I've posted.
