### ISSUE TITLE
useReducer accumulator stale if initial function ref is reused

### ISSUE THREAD

**Issue by fuzetsu** [WebReflection/augmentor#25]
```js
import { neverland as $, html, render, useReducer, useEffect } from 'neverland'

const app = $(() => {
  const [count, inc] = useReducer(c => c + 1, 0)
  
  useEffect(() => {
    // inc does not work after first call, because of stale accumulator
    // since implementation relies on `useState`
    const id = setInterval(inc, 500)
    return () => clearInterval(id)
  }, [])
  
  return html`<h1>The count is ${count}</h1>`
})

render(document.body, app)
```
[live example](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4IWAA60ATsQAEwOWhgA3GNKgY0AEzkY4cgCQU5JMielNt6kwFc4MAEoxtt6jbn2YAUTBgY1PKscmDStFhyAOTKahpa2pEAOmjJQnDyGBIScgC8RgAU+QCUuQB8CslycmnyyHS2DCYQaNQAurmeDs6u7tL51GVyEv1yANRyAIwmkc3UljgMzQDmkUUmAAxFlXLbXr7+gYUlOeXA21UA9Bdys3LatPBKtPIA7jIA1npgjNIhENLpaoYKBQEwAIwCGC8N3kligEEe9Dk6WBME6MAAysQMIw5CpgbY0c0bpJYAtscQIPRztV6ICILo8g5iABJYTSfFQfKzEwAVnWmxplmItmkaDkxUG1FgGGkbJ+nO52i24rk7DkyFaKqq22FovFZigAAMADyECalAAqhDR9QYNwMhmAduIrBNF3NpSNyVYKuSlh06ny92otnJ+DBtG0AE8TJkJEVKCAHLBAlS0AgeBMACyIABMADY2BwQJgcHh8NQ4AIaPRGMweGxWqwgA)

It might make sense to treat `useReducer` as the base implementation and have `useState` call `useReducer`.. 🤔 

[This is what preact does.](https://github.com/preactjs/preact/blob/b69fc9772d9cafe36d1d9fa9859f84a90ecf8feb/hooks/src/index.js#L107-L109)

Also as a side note, have you considered making `useState`/`useReducer` return a consistent function reference, like React's/Preact's hook implementations?

**Comment by WebReflection** [comment]
> It might make sense to treat `useReducer` as the base implementation and have `useState` call `useReducer`.. 

it might be a possibility but what would it change?

> Also as a side note, have you considered making useState/useReducer return a consistent function reference, like React's/Preact's hook implementations?

do you mean having the same function each time instead of a new one? if the options can't change by contract, which I'm not sure about but it seems to be the case, it looks like a reasonable optimization.

Regarding the issue, I guess you asked about the rest so that you could pass `[inc]` as guard, but why don't you pass nothing instead, or `[count]` ?

The `useEffect` is currently detached from other states, but if the thing is expected to change each time, I think it makes little sense to pass `[]` in `useState`, as that's for _never change_, which is indeed what happens in here.

What am I missing?

**Comment by WebReflection** [comment]
FYI I've now used `useReducer` as base, and also creating the callback once, yet I believe this won't change the issue here, am I correct?

**Comment by fuzetsu** [comment]
> it might be a possibility but what would it change?

Nothing necessarily, just suggested it because I was looking at how I'd go about PR'ing it, and it seemed to me easier to fix this bug by treating `useReducer` as the base implementation.

> do you mean having the same function each time instead of a new one?

Exactly. Minor optimization + could prevent issues with common hook gotchas:

For example in React, it's not necessary or even recommend to include a setter in the deps array of a `useEffect`, since React guarantees that the setter will always be the same instance:
```js
const [changed, setChanged] = useState(false)
const [count, setCount] = useState(0)
useEffect(() => setChanged(true), [count, setChanged])
```
But some people put it in anyway, and it works fine because it's the same function (doesn't rerun the effect each redraw). But if a new function is returned each redraw then the effect will run every time instead of just when count changes. 

> Regarding the issue, I guess you asked about the rest so that you could pass [inc] as guard, but why don't you pass nothing instead, or [count] ?

Sorry, I was asking about the consistent reference stuff as an aside as well, not actually related to this issue. The core thing was just that the example code I expected to work didn't. Despite the same code working in preact/react. 

So I looked at the`useReducer` implementation and saw it was relying on a variable in an outer scope instead of using a ref object or similar.

https://github.com/WebReflection/augmentor/blob/0cf8d9feea8302dbce4527b8284559da6db64bc5/esm/index.js#L72-L80
The `pair[0]` on line 78, relied on the original pair in scope. 



All that said, the changes you made to return a consistent function, and to `useReducer` as the base implementation have fixed this. You can see my [live example](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4IWAA60ATsQAEwOWhgA3GNKgY0AEzkY4cgCQU5JMielNt6kwFc4MAEoxtt6jbn2YAUTBgY1PKscmDStFhyAOTKahpa2pEAOmjJQnDyGBIScgC8RgAU+QCUuQB8CslycmnyyHS2DCYQaNQAurmeDs6u7tL51GVyEv1yANRyAIwmkc3UljgMzQDmkUUmAAxFlXLbXr7+gYUlOeXA21UA9Bdys3LatPBKtPIA7jIA1npgjNIhENLpaoYKBQEwAIwCGC8N3kligEEe9Dk6WBME6MAAysQMIw5CpgbY0c0bpJYAtscQIPRztV6ICILo8g5iABJYTSfFQfKzEwAVnWmxplmItmkaDkxUG1FgGGkbJ+nO52i24rk7DkyFaKqq22FovFZigAAMADyECalAAqhDR9QYNwMhmAduIrBNF3NpSNyVYKuSlh06ny92otnJ+DBtG0AE8TJkJEVKCAHLBAlS0AgeBMACyIABMADY2BwQJgcHh8NQ4AIaPRGMweGxWqwgA) works now 🎉 

Thank you!

**Comment by WebReflection** [comment]
So it was fixed ... great, closing this then 👋
