### ISSUE TITLE
Nested context providers don't restore previous context value

### ISSUE THREAD

**Issue by MessagingMoore** [WebReflection/augmentor#27]
Nested context providers don't restore previous context value after executing.

```
import { augmentor, createContext, useContext } from 'augmentor';

const TestContext = createContext();

const RootProvider = augmentor(() => {
  TestContext.provide("hello world");
  ChildProvider();
  Consume();
});

const ChildProvider = augmentor(() => {
  TestContext.provide("last update wins");
  Consume();
});

const Consume = augmentor(() => {
  const message = useContext(TestContext);
  console.log(message);
});

RootProvider();
```

Actual Output

```
last hello wins 
last hello wins
```

Expected output
```
last hello wins 
hello world
```

Changing the root to this:
```
const RootProvider = augmentor(() => {
  TestContext.provide("hello world");
  Consume();
  ChildProvider();
  Consume();
});
```
Produces output I truly wouldn't expect:

```
hello world 
last hello wins 
last hello wins 
last hello wins 
```
An extra invocation, no?

**Comment by WebReflection** [comment]
are these two bugs or one?

**Comment by WebReflection** [comment]
OK, after thinking about this, and reading again React documentation regarding `context`, I think the paradigm here is slightly different.

Basically, what you are doing, is like representing what a `<Provider value={value}>` would mean in the JSX world, but here `context.provide(value)` is actually the one that triggers updates, not the one you should set before manually invoking updates, can you see the difference?

The following, as example, would make more sense for your use case:
```js
import { augmentor, createContext, useContext } from 'augmentor';

const TestContext = createContext();

const ChildProvider = $(() => {
  Consume();
});

const Consume = $(() => {
  const message = useContext(TestContext);
  console.log(message);
});

// dummy example, no meaning, logs undefined
ChildProvider();
Consume();

// now you can trigger the augmented function
// that is using a context
TestContext.provide("hello world");
// logs "hello world"

TestContext.provide("last update");
// logs "last update"
```
In few words, in `augmentor` the _context_ is meant to drive update, it doesn't need to be set on top of updates.

If I change this, it's be likely a complete surprise for anyone else using _context_ in here, and there's no way to dispatch and ignore updates simultaneously.

What do you think?

**Comment by WebReflection** [comment]
As no answer was provided, I'll just close this.
