### ISSUE TITLE
Can async functions be augmented ?

### ISSUE THREAD

**Issue by strowbeary** [WebReflection/augmentor#29]
Hello,
I have a question about augmented async functions
```js
augmentor(() => {
    myAsyncFunction().then(() => {});
})
```

myAsyncFunction containing `useState` hook

**Comment by WebReflection** [comment]
no, and neither can React, last time I've checked. This breaks hooks https://webreflection.medium.com/demystifying-hooks-f55ad885609f

use all states and hooks synchronously and pass these along if needed asynchronously.
