### ISSUE TITLE
docs for creating custom hooks

### ISSUE THREAD

**Issue by dakom** [WebReflection/augmentor#3]
not really clear on what `stacked`, `unstacked`, `update`, and `i` are all about...

**Comment by dakom** [comment]
on the same topic - if I want to create a hook that builds off `dom-augmentor`, do I somehow get those functions from there rather than here?

**Comment by dakom** [comment]
I think I can answer the second question... when installing neverland, dom-augmentor and augmentor are installed as dependencies.

Using typescript, I was not able to get at the above functions via `import {setup, stacked, unstacked, uid} from 'augmentor/core.js';`

However, this did work for me:

```
import {setup, stacked, unstacked, uid} from "augmentor/esm/core";
```

**Comment by dakom** [comment]
Attempted to figure it out but couldn't get it... here's what I've got so far (idea is just to store a variable for emulating state):

```
import neverland, {render, html, useState, useEffect, useRef} from 'neverland';
import {setup, stacked, unstacked, uid} from "augmentor/esm/core";

//create the hook

export const useCustom = initialState => {
  const {i, stack, update, unknown} = unstacked(id);
  if (unknown) {
    const stateRef = useRef();

    useEffect(() => {
        stateRef.current = initialState;
    }, []);

    const setState = value => {
        stateRef.current = value;
        update();
    }

    stack.push([stateRef.current, setState]);
  }
  // return the current stack position at index `i`
  return stack[i];
};


//use the hook
const Display = neverland(() => {
    const [state, updateState] = useCustom("Waiting...");

    return html`
        <button onClick=${() => updateState("clicked!")}>${state}</button>
    `;
});

render(document.getElementById("app"), Display);
```

**Comment by dakom** [comment]
Yes- the above example is just meant as a getting started.

The actual use case I have in mind is to wrap up a slightly more advanced pattern of useRef, useEffect, and useState, around a state management library (xstate) so that I can use that abstraction as a simple hook instead of copy/pasting those ~12 lines of code each time

**Comment by joshgillies** [comment]
Actually, reviewing my notes from last night I did have to change the `useMachine` hook a little before it would work as expected.

See below:

```js
const {default: $, useEffect, useMemo, useRef, useState} = augmentor;
const {render, hook} = lighterhtml;
const {html, svg} = hook(useRef);

const { Machine} = XState;
const { interpret } = XStateInterpreter;

const toggleMachine = Machine({
  id: 'toggle',
  initial: 'inactive',
  states: {
    inactive: {
      on: { TOGGLE: 'active' }
    },
    active: {
      on: { TOGGLE: 'inactive' }
    }
  }
});

function useMachine(machine) {
  // Keep track of the current machine state
  const [current, setCurrent] = useState(machine.initialState);

  // Start the service (only once!)
  const service = useMemo(
    () =>
      interpret(machine)
        .onTransition(state => {
          // Update the current machine state when a transition occurs
          setCurrent(state);
        })
        ,
    []
  );

  // Stop the service when the component unmounts
  useEffect(() => {
    service.start()
    return () => service.stop();
  }, []);

  return [current, service.send];
}

const Toggle = () => $(() => {
  const [current, send] = useMachine(toggleMachine);
  return html`
    <button onclick=${() => send('TOGGLE')}>
      ${current.matches('inactive') ? 'Off' : 'On'}
    </button>
  `;
})

const toggle = Toggle();

render(document.body, toggle);
```

**Comment by dakom** [comment]
Oh wow- that's almost exactly what I was looking for just that I was using useRef instead of useMemo

So the takeaway seems to be that all the stack/unstack stuff isn't needed to roll your own hooks?

Would be great to have that clarified in the docs.

Thanks for pointing me in the right direction. Exciting!

I almost _want_ to go into work today ;)

**Comment by joshgillies** [comment]
Nice, I suspect the next challenge will be passing context through your UI. Good thing there's discussion on this exact topic already over at #2 !

Admittedly, the idea behind `augmentor` is to be general purpose tooling for `hooks`, so exposing `stack`/`unstack` for custom hooks would be appreciated assuming you want to go to that level. From reviewing the react community thought, it's pretty clear 90% of what they are doing is based purely off the back of the standard set of `use*` hooks.

**Comment by dakom** [comment]
With that in mind I think this issue can be closed with exactly a line like that, and then a bit of explanation of why and how one might reach for `stack/unstack/etc.` in the edge cases

**Comment by WebReflection** [comment]
I've updated the README with this text:

> Beside using any of the already implemented hooks to create your own would work just fine,
you could also take advantage of internals used to create other hooks.
> 
> The _augmentor_ core provides indeed utilities to make your own hook, for your own library, and export these like any other.
