### ISSUE TITLE
Why would values be undefined in createEffect?

### ISSUE THREAD

**Issue by luke-thorburn** [WebReflection/augmentor#30]
I'm building a moderately sized app using [neverland](https://github.com/WebReflection/neverland), and am encountering an error that seems to be triggered by the augmentor code.

Specifically, the use of `useEffect` sometimes triggers the following error:

    index.js:192 Uncaught TypeError: Cannot read property '0' of undefined
        at different (index.js:192)
        at Array.some (<anonymous>)
        at index.js:123
        at SelectSubField (DefaultCollection_Doc_SelectSubField.js:60)
        at SubField (DefaultCollection_Doc_SequenceField.js:193)
        at DefaultCollection_Doc_SequenceField.js:251
        at Array.map (<anonymous>)
        at DefaultCollection_Doc_SequenceField.js:247
        at Array.map (<anonymous>)
        at Element (DefaultCollection_Doc_SequenceField.js:244)

Which I have traced back to the `createEffect` function in augmentor:

```js
const createEffect = asy => (effect, guards) => {
  const i = state.i++;
  const {hook, after, stack, length} = state;
  if (i < length) {
    const info = stack[i];
    const {update, values, stop} = info;
    if (!guards || guards.some(different, values)) {
      // ^^^ Error is triggered on the previous line because 'values' is undefined. ^^^
      // ...
```

It will be quite a lot of work to create a minimal example so before I do I thought I would ask: can you think of any reason why `values` would be undefined?

**Comment by WebReflection** [comment]
> can you think of any reason why values would be undefined?

conditional hooks (ternary, hooks within hooks that are guarded hence don't always execute, or any condition where the hook is not always used).

you could try to see if you have the same in [µland](https://github.com/WebReflection/uland#readme) which is based on [µhooks](https://github.com/WebReflection/uhooks#readme) instead, and if the problem is still there, then this is likely the answer.

**Comment by luke-thorburn** [comment]
Thanks @WebReflection, this helped me resolve the problem well enough for now (by tweaking some of the guarding variables).
