### ISSUE TITLE
useState causing whole node to change

### ISSUE THREAD

**Issue by dakom** [WebReflection/augmentor#8]
Picking up from #2 - but without any of the `useMemo` or `useContext` complexity - it seems that `useState` itself (or maybe with `useEffect`?) is causing entire dom nodes to re-render when state changes.

See: https://codepen.io/dakom/pen/bOyzqd

**Comment by WebReflection** [comment]
so, version `1.0.6` uses the effect _after_, on next tick, right before. I hope that works, but I have to go now so we'll see in the future 👋

**Comment by WebReflection** [comment]
I see the issue doesn't seem to be solved, but I really have to go now so I'll try to figure out what the hell is going on, since other demos are just fine.

Take of the day: magic is hard.

**Comment by luwes** [comment]
I stumbled on the same issue today with nesting

**Comment by WebReflection** [comment]
closing this as it's not strictly related to augmenter and the demo uses neverland, which is another project
