### ISSUE TITLE
useEffect cleanup - wierd behaviour?

### ISSUE THREAD

**Issue by vbargl** [WebReflection/augmentor#9]
I was just experimenting and found out that `useEffect` does not have same behaviour as React's `useEffect`.
I hope I did not misunderstood anything, but cleanup of useEffect hook completely ignores inputs and fires at next run. I have sandboxed two application with same (expected) behavior for augmentor and react.

Augmentor: https://codesandbox.io/s/p2rnn4oy40
React: https://codesandbox.io/s/qx2zm1o57q

**Comment by WebReflection** [comment]
Thanks, this was puzzling me as well, but I didn't have a proper comparison / test for it, now I do.

**Comment by WebReflection** [comment]
P.S. it should be fixed now
